-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Nameless.

module Syntax.Nameless.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = ProgramExprs Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
    = Seq [Expr]
    | If Expr Expr Expr
    | Abstraction Type Expr
    | Assign Expr Expr
    | Application Expr Expr
    | NewRef Expr
    | DeRef Expr
    | Succ Expr
    | Pred Expr
    | IsZero Expr
    | ConstUnit
    | ConstTrue
    | ConstFalse
    | ConstZero
    | FreeVar Ident
    | BoundVar Integer
    | Location Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Store = Store [Assignment]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Assignment = Assignment Integer Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data StoreTyping = StoreTyping [LocationTyping]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LocationTyping = LocationTyping Integer Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type
    = FunType Type Type | RefType Type | BoolType | NatType | UnitType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Typing = Typing Expr Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

