package Syntax.normal.Absyn; // Java Package generated by the BNF Converter.

public class Abstraction  extends Expr {
  public final String ident_;
  public final Expr expr_;
  public Abstraction(String p1, Expr p2) { ident_ = p1; expr_ = p2; }

  public <R,A> R accept(Syntax.normal.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof Syntax.normal.Absyn.Abstraction) {
      Syntax.normal.Absyn.Abstraction x = (Syntax.normal.Absyn.Abstraction)o;
      return this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.expr_.hashCode();
  }


}
