package Syntax.normal.Absyn; // Java Package generated by the BNF Converter.

public class ProgramExprs  extends Program {
  public final ListExpr listexpr_;
  public ProgramExprs(ListExpr p1) { listexpr_ = p1; }

  public <R,A> R accept(Syntax.normal.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof Syntax.normal.Absyn.ProgramExprs) {
      Syntax.normal.Absyn.ProgramExprs x = (Syntax.normal.Absyn.ProgramExprs)o;
      return this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.listexpr_.hashCode();
  }


}
