package Syntax.normal.Absyn; // Java Package generated by the BNF Converter.

public class Var  extends Expr {
  public final String ident_;
  public Var(String p1) { ident_ = p1; }

  public <R,A> R accept(Syntax.normal.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof Syntax.normal.Absyn.Var) {
      Syntax.normal.Absyn.Var x = (Syntax.normal.Absyn.Var)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
