package Syntax.nameless.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Syntax.nameless.Absyn.ConstTrue p, A arg);
    public R visit(Syntax.nameless.Absyn.ConstFalse p, A arg);
    public R visit(Syntax.nameless.Absyn.If p, A arg);
    public R visit(Syntax.nameless.Absyn.ConstZero p, A arg);
    public R visit(Syntax.nameless.Absyn.Succ p, A arg);
    public R visit(Syntax.nameless.Absyn.Pred p, A arg);
    public R visit(Syntax.nameless.Absyn.IsZero p, A arg);
    public R visit(Syntax.nameless.Absyn.FreeVar p, A arg);
    public R visit(Syntax.nameless.Absyn.BoundVar p, A arg);
    public R visit(Syntax.nameless.Absyn.Abstraction p, A arg);
    public R visit(Syntax.nameless.Absyn.Application p, A arg);

  }

}
