package Syntax.nameless.Absyn; // Java Package generated by the BNF Converter.

public class FreeVar  extends Expr {
  public final String ident_;
  public FreeVar(String p1) { ident_ = p1; }

  public <R,A> R accept(Syntax.nameless.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof Syntax.nameless.Absyn.FreeVar) {
      Syntax.nameless.Absyn.FreeVar x = (Syntax.nameless.Absyn.FreeVar)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
