/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"


namespace Nameless
{
void Skeleton::visitExpr(Expr *t) {} //abstract class

void Skeleton::visitConstTrue(ConstTrue *const_true)
{
  /* Code For ConstTrue Goes Here */


}

void Skeleton::visitConstFalse(ConstFalse *const_false)
{
  /* Code For ConstFalse Goes Here */


}

void Skeleton::visitIf(If *if_)
{
  /* Code For If Goes Here */

  if (if_->expr_1) if_->expr_1->accept(this);
  if (if_->expr_2) if_->expr_2->accept(this);
  if (if_->expr_3) if_->expr_3->accept(this);

}

void Skeleton::visitConstZero(ConstZero *const_zero)
{
  /* Code For ConstZero Goes Here */


}

void Skeleton::visitSucc(Succ *succ)
{
  /* Code For Succ Goes Here */

  if (succ->expr_) succ->expr_->accept(this);

}

void Skeleton::visitPred(Pred *pred)
{
  /* Code For Pred Goes Here */

  if (pred->expr_) pred->expr_->accept(this);

}

void Skeleton::visitIsZero(IsZero *is_zero)
{
  /* Code For IsZero Goes Here */

  if (is_zero->expr_) is_zero->expr_->accept(this);

}

void Skeleton::visitFreeVar(FreeVar *free_var)
{
  /* Code For FreeVar Goes Here */

  visitIdent(free_var->ident_);

}

void Skeleton::visitBoundVar(BoundVar *bound_var)
{
  /* Code For BoundVar Goes Here */

  visitInteger(bound_var->integer_);

}

void Skeleton::visitAbstraction(Abstraction *abstraction)
{
  /* Code For Abstraction Goes Here */

  if (abstraction->expr_) abstraction->expr_->accept(this);

}

void Skeleton::visitApplication(Application *application)
{
  /* Code For Application Goes Here */

  if (application->expr_1) application->expr_1->accept(this);
  if (application->expr_2) application->expr_2->accept(this);

}



void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}


}
