/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2

namespace Nameless
{
//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitProgram(Program *p) {} //abstract class

void PrintAbsyn::visitProgramExprs(ProgramExprs *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  _i_ = 0; visitListExpr(p->listexpr_);

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListExpr(ListExpr *listexpr)
{
  iterListExpr(listexpr->begin(), listexpr->end());
}

void PrintAbsyn::iterListExpr(ListExpr::const_iterator i, ListExpr::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(';'); iterListExpr(i+1, j);
  }
}

void PrintAbsyn::visitExpr(Expr *p) {} //abstract class

void PrintAbsyn::visitIf(If *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  render("if");
  _i_ = 0; p->expr_1->accept(this);
  render("then");
  _i_ = 0; p->expr_2->accept(this);
  render("else");
  _i_ = 0; p->expr_3->accept(this);

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLet(Let *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  render("let");
  _i_ = 0; p->expr_1->accept(this);
  render("in");
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAbstraction(Abstraction *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  render("fun");
  render('(');
  _i_ = 0; p->type_->accept(this);
  render(')');
  render('{');
  render("return");
  _i_ = 0; p->expr_->accept(this);
  render('}');

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRecord(Record *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  render('{');
  _i_ = 0; visitListBindingExpr(p->listbindingexpr_);
  render('}');

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitApplication(Application *p)
{
  int oldi = _i_;
  if (oldi > 1) render(NAMELESS__L_PAREN);

  _i_ = 1; p->expr_1->accept(this);
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 1) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSucc(Succ *p)
{
  int oldi = _i_;
  if (oldi > 2) render(NAMELESS__L_PAREN);

  render("succ");
  _i_ = 3; p->expr_->accept(this);

  if (oldi > 2) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDot(Dot *p)
{
  int oldi = _i_;
  if (oldi > 2) render(NAMELESS__L_PAREN);

  _i_ = 3; p->expr_->accept(this);
  render('.');
  visitIdent(p->ident_);

  if (oldi > 2) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPred(Pred *p)
{
  int oldi = _i_;
  if (oldi > 2) render(NAMELESS__L_PAREN);

  render("pred");
  _i_ = 3; p->expr_->accept(this);

  if (oldi > 2) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIsZero(IsZero *p)
{
  int oldi = _i_;
  if (oldi > 2) render(NAMELESS__L_PAREN);

  render("iszero");
  _i_ = 3; p->expr_->accept(this);

  if (oldi > 2) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstTrue(ConstTrue *p)
{
  int oldi = _i_;
  if (oldi > 3) render(NAMELESS__L_PAREN);

  render("true");

  if (oldi > 3) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstFalse(ConstFalse *p)
{
  int oldi = _i_;
  if (oldi > 3) render(NAMELESS__L_PAREN);

  render("false");

  if (oldi > 3) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstZero(ConstZero *p)
{
  int oldi = _i_;
  if (oldi > 3) render(NAMELESS__L_PAREN);

  render('0');

  if (oldi > 3) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFreeVar(FreeVar *p)
{
  int oldi = _i_;
  if (oldi > 3) render(NAMELESS__L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 3) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBoundVar(BoundVar *p)
{
  int oldi = _i_;
  if (oldi > 3) render(NAMELESS__L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 3) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBindingExpr(BindingExpr *p) {} //abstract class

void PrintAbsyn::visitBinding(Binding *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListBindingExpr(ListBindingExpr *listbindingexpr)
{
  iterListBindingExpr(listbindingexpr->begin(), listbindingexpr->end());
}

void PrintAbsyn::iterListBindingExpr(ListBindingExpr::const_iterator i, ListBindingExpr::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListBindingExpr(i+1, j);
  }
}

void PrintAbsyn::visitType(Type *p) {} //abstract class

void PrintAbsyn::visitFunType(FunType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  _i_ = 1; p->type_1->accept(this);
  render("->");
  _i_ = 0; p->type_2->accept(this);

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRecordType(RecordType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  render('{');
  _i_ = 0; visitListFieldTypeExpr(p->listfieldtypeexpr_);
  render('}');

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBoolType(BoolType *p)
{
  int oldi = _i_;
  if (oldi > 1) render(NAMELESS__L_PAREN);

  render("Bool");

  if (oldi > 1) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitNatType(NatType *p)
{
  int oldi = _i_;
  if (oldi > 1) render(NAMELESS__L_PAREN);

  render("Nat");

  if (oldi > 1) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFieldTypeExpr(FieldTypeExpr *p) {} //abstract class

void PrintAbsyn::visitFieldType(FieldType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListFieldTypeExpr(ListFieldTypeExpr *listfieldtypeexpr)
{
  iterListFieldTypeExpr(listfieldtypeexpr->begin(), listfieldtypeexpr->end());
}

void PrintAbsyn::iterListFieldTypeExpr(ListFieldTypeExpr::const_iterator i, ListFieldTypeExpr::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListFieldTypeExpr(i+1, j);
  }
}

void PrintAbsyn::visitTyping(Typing *p) {} //abstract class

void PrintAbsyn::visitTypingStmt(TypingStmt *p)
{
  int oldi = _i_;
  if (oldi > 0) render(NAMELESS__L_PAREN);

  _i_ = 0; p->expr_->accept(this);
  render(':');
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(NAMELESS__R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitProgram(Program *p) {} //abstract class

void ShowAbsyn::visitProgramExprs(ProgramExprs *p)
{
  bufAppend('(');
  bufAppend("ProgramExprs");
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpr_)  p->listexpr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListExpr(ListExpr *listexpr)
{
  for (ListExpr::const_iterator i = listexpr->begin() ; i != listexpr->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listexpr->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitExpr(Expr *p) {} //abstract class

void ShowAbsyn::visitIf(If *p)
{
  bufAppend('(');
  bufAppend("If");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  p->expr_3->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLet(Let *p)
{
  bufAppend('(');
  bufAppend("Let");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitAbstraction(Abstraction *p)
{
  bufAppend('(');
  bufAppend("Abstraction");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRecord(Record *p)
{
  bufAppend('(');
  bufAppend("Record");
  bufAppend(' ');
  bufAppend('[');
  if (p->listbindingexpr_)  p->listbindingexpr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitApplication(Application *p)
{
  bufAppend('(');
  bufAppend("Application");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitSucc(Succ *p)
{
  bufAppend('(');
  bufAppend("Succ");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitDot(Dot *p)
{
  bufAppend('(');
  bufAppend("Dot");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitPred(Pred *p)
{
  bufAppend('(');
  bufAppend("Pred");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitIsZero(IsZero *p)
{
  bufAppend('(');
  bufAppend("IsZero");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitConstTrue(ConstTrue *p)
{
  bufAppend("ConstTrue");
}
void ShowAbsyn::visitConstFalse(ConstFalse *p)
{
  bufAppend("ConstFalse");
}
void ShowAbsyn::visitConstZero(ConstZero *p)
{
  bufAppend("ConstZero");
}
void ShowAbsyn::visitFreeVar(FreeVar *p)
{
  bufAppend('(');
  bufAppend("FreeVar");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitBoundVar(BoundVar *p)
{
  bufAppend('(');
  bufAppend("BoundVar");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitBindingExpr(BindingExpr *p) {} //abstract class

void ShowAbsyn::visitBinding(Binding *p)
{
  bufAppend('(');
  bufAppend("Binding");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListBindingExpr(ListBindingExpr *listbindingexpr)
{
  for (ListBindingExpr::const_iterator i = listbindingexpr->begin() ; i != listbindingexpr->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listbindingexpr->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitType(Type *p) {} //abstract class

void ShowAbsyn::visitFunType(FunType *p)
{
  bufAppend('(');
  bufAppend("FunType");
  bufAppend(' ');
  p->type_1->accept(this);
  bufAppend(' ');
  p->type_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitRecordType(RecordType *p)
{
  bufAppend('(');
  bufAppend("RecordType");
  bufAppend(' ');
  bufAppend('[');
  if (p->listfieldtypeexpr_)  p->listfieldtypeexpr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitBoolType(BoolType *p)
{
  bufAppend("BoolType");
}
void ShowAbsyn::visitNatType(NatType *p)
{
  bufAppend("NatType");
}
void ShowAbsyn::visitFieldTypeExpr(FieldTypeExpr *p) {} //abstract class

void ShowAbsyn::visitFieldType(FieldType *p)
{
  bufAppend('(');
  bufAppend("FieldType");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListFieldTypeExpr(ListFieldTypeExpr *listfieldtypeexpr)
{
  for (ListFieldTypeExpr::const_iterator i = listfieldtypeexpr->begin() ; i != listfieldtypeexpr->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listfieldtypeexpr->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitTyping(Typing *p) {} //abstract class

void ShowAbsyn::visitTypingStmt(TypingStmt *p)
{
  bufAppend('(');
  bufAppend("TypingStmt");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}

}
